---
- hostname: name={{ hostname }}

- name: Update apt database 
  action: apt update_cache=yes
  tags: apt

- name: Upgrade packages
  action: apt upgrade=full
  tags: apt

- name: Install common packages 
  action: apt pkg={{ item }} state=installed
  with_items:
    - vim
    - sudo
    - ntp
    - tcpdump
  tags: common 

- name: MOTD
  action: template src=motd.j2 dest=/etc/motd
  tags:
    - motd_config

- name: Interfaces
  action: template src=interfaces dest=/etc/network/interfaces

- name: Install key zarya
  action: authorized_key user=zarya key="{{ lookup('file', "/home/zarya/.ssh/id_dsa.pub" ) }}"

- name: Install key zarya
  action: authorized_key user=root key="{{ lookup('file', "/home/zarya/.ssh/id_dsa.pub" ) }}"

- name: Install key network 
  action: authorized_key user=root key="{{ lookup('file', "/home/zarya/seafile/Hytera/VPN Infra/ssh/id_dsa.pub" ) }}"
